import type { FrameVersion, FrameVersionCatalog } from '@/types/template';

/**
 * Hand-curated index of frame versions, derived from
 * `src/legacy-app/data/scripts/versions/*` directory names. The legacy
 * editor loads each version's `.js` payload on demand; the catalog below is
 * intentionally just metadata so it stays decoupled from the editor port.
 */
export const FRAME_VERSIONS: readonly FrameVersion[] = [
  { id: 'm15', label: 'Regular Frames', group: 'Regular' },
  { id: 'm15Nyx', label: 'Enchantment Frames (Nyx)', group: 'Regular' },
  { id: 'm15LegendCrowns', label: 'Legend Crowns', group: 'Regular' },
  { id: 'm15FloatingCrowns', label: 'Floating Legend Crowns', group: 'Regular' },
  { id: 'm15InnerCrowns', label: 'Inner Crowns', group: 'Regular' },
  { id: 'm15Nickname', label: 'Nicknames', group: 'Regular' },
  { id: 'm15SmoothNicknameLegendCrowns', label: 'Smooth Nickname Legend Crowns', group: 'Regular' },
  { id: 'm15Miracle', label: 'Miracle', group: 'Regular' },
  { id: 'm15HoloStamps', label: 'Holo Stamps', group: 'Regular' },
  { id: 'm15DarkPT', label: 'Dark Power/Toughness', group: 'Regular' },
  { id: 'm15ColoredBorders', label: 'Colored Borders', group: 'Regular' },
  { id: 'm15ColorIdentityPips', label: 'Color Identity Pips', group: 'Regular' },
  { id: 'm15TheListStamp', label: '"The List" Stamp', group: 'Regular' },
  { id: 'm15Lands', label: 'Lands', group: 'Regular' },
  { id: 'm15Stations', label: 'Stations', group: 'Regular' },
  { id: 'm15BorderlessStations', label: 'Borderless Stations', group: 'Regular' },
  { id: 'm15Omens', label: 'Omens (Tarkir Dragonstorm)', group: 'Regular' },
  { id: 'm15Rooms', label: 'Rooms (Duskmourn)', group: 'Regular' },
  { id: 'm15Spree', label: 'Spree (Outlaws of Thunder Junction)', group: 'Regular' },
  { id: 'm15Cases', label: 'Cases (Murders at Karlov Manor)', group: 'Regular' },
  { id: 'm15Battle', label: 'Battle (March of the Machine)', group: 'Regular' },
  { id: 'm15Prototype', label: "Prototype (Brothers' War)", group: 'Regular' },
  { id: 'm15PrototypeExtended', label: "Prototype (Extended Art) (Brothers' War)", group: 'Regular' },
  { id: 'm15Attractions', label: 'Attractions (Unfinity)', group: 'Regular' },
  { id: 'm15Class', label: 'Class (D&D)', group: 'Regular' },
  { id: 'm15Snow', label: 'Snow (Kaldheim)', group: 'Regular' },
  { id: 'm15Mutate', label: 'Mutate (Ikoria)', group: 'Regular' },
  { id: 'm15Adventures', label: 'Adventures (Eldraine)', group: 'Regular' },
  { id: 'm15Devoid', label: 'Devoid (Zendikar)', group: 'Regular' },
  { id: 'm15Aftermath', label: 'Aftermath (Amonkhet)', group: 'Regular' },
  { id: 'm15Flip', label: 'Flip (Kamigawa)', group: 'Regular' },
  { id: 'm15Levelers', label: 'Levelers (Zendikar)', group: 'Regular' },
  { id: 'm15Split', label: 'Split Cards', group: 'Regular' },
  { id: 'm15Fuse', label: 'Fuse Cards', group: 'Regular' },
  { id: 'm15Conspiracies', label: 'Conspiracies (Draft Matters)', group: 'Regular' },
  { id: 'm15Colorshifted', label: 'Colorshifted (Planar Chaos)', group: 'Regular' },
  { id: 'm15BrawlLegendCrowns', label: 'Brawl Legend Crowns', group: 'Regular' },
  { id: 'short', label: 'Extended Art (Shorter Textbox)', group: 'Misc' },
  { id: 'm15Planeswalker', label: 'Regular', group: 'Planeswalker' },
  { id: 'modal', label: 'MDFC', group: 'DFC' },
  { id: 'm15TransformFront', label: 'Regular (Front)', group: 'Transform' },
  { id: 'm15TransformBack', label: 'Regular (Back)', group: 'Transform' },
  { id: 'm15TransformIcons', label: 'Transform Icons', group: 'Transform' },
  { id: 'saga', label: 'Regular Frames', group: 'Saga' },
  { id: 'sagaNyx', label: 'Nyx Frames', group: 'Saga' },
  { id: 'sagaUB', label: 'Universes Beyond Frames', group: 'Saga' },
  { id: 'm15Promo', label: 'M15 Promo', group: 'Promo' },
  { id: 'm15PromoOpenHouse', label: 'M15 Promo Open House', group: 'Promo' },
  { id: 'm15PromoNyx', label: 'M15 Promo Nyx', group: 'Promo' },
  { id: 'm15PromoExtended', label: 'M15 Promo Extended', group: 'Promo' },
  { id: 'm15PromoGenericShowcase', label: 'M15 Promo Generic Showcase', group: 'Promo' },
  { id: 'm15Textless', label: 'M15 Textless Generic Showcase', group: 'Textless' },
  { id: 'm15TextlessBasics', label: 'M15 Textless Basics', group: 'Textless' },
  { id: 'm15TextlessBasics2022', label: 'M15 Textless Basics 2022', group: 'Textless' },
  { id: 'm15TextlessBasics2022UB', label: 'M15 Textless Basics 2022 UB', group: 'Textless' },
  { id: 'equinoxTextless', label: 'Equinox Textless', group: 'Textless' },
  { id: 'storybook', label: 'Storybook', group: 'Showcase' },
  { id: 'expedition', label: 'Expedition', group: 'Showcase' },
  { id: 'ixalan', label: 'Ixalan', group: 'Showcase' },
  { id: 'future', label: 'Future Sight', group: 'Showcase' },
  { id: 'm15UB', label: 'Universes Beyond', group: 'UniversesBeyond' },
  { id: 'm15UBFull', label: 'Universes Beyond (Full art)', group: 'UniversesBeyond' },
  { id: 'm15UBExtended', label: 'Universes Beyond (Extended art)', group: 'UniversesBeyond' },
  { id: 'm15UBLegendCrowns', label: 'Legend Crowns (Universes Beyond)', group: 'UniversesBeyond' },
  { id: 'm15UBFloatingCrowns', label: 'Floating Legend Crowns (Universes Beyond)', group: 'UniversesBeyond' },
  { id: 'legends', label: 'Legends', group: 'Misc' },
  { id: 'seventh', label: 'Seventh Edition', group: 'Misc' },
  { id: 'seventhTextless', label: 'Seventh Edition Textless', group: 'Misc' },
  { id: 'unstable', label: 'Unstable', group: 'Misc' },
  { id: 'bleedEdge', label: 'Bleed Edge', group: 'Misc' },
  { id: 'planechase', label: 'Planechase', group: 'Misc' },
  { id: 'customAddons', label: 'Custom Addons', group: 'Custom' },
  { id: 'accurateM15', label: 'Regular Frames', group: 'Accurate' },
  { id: 'marginM15', label: 'Regular Frames', group: 'Margin' },
  { id: 'fleshAndBlood', label: 'Flesh and Blood', group: 'FleshAndBlood' },
  { id: 'token', label: 'Token', group: 'Token' },
];

export function loadFrameVersionCatalog(): FrameVersionCatalog {
  return { versions: FRAME_VERSIONS };
}
