import fsp from 'node:fs/promises';
import path from 'node:path';
import { repoRoot, toNativePath } from './project.mjs';

export const creatorCompatModulePaths = [
  'src/creator/assets/asset-url.mjs',
  'src/creator/assets/frame-preload.mjs',
  'src/creator/text/text-fonts.mjs',
  'src/creator/text/write-text-content.mjs',
  'src/creator/text/write-text-conditional-color.mjs',
  'src/creator/text/write-text-style.mjs',
  'src/creator/text/write-text-mana.mjs',
  'src/creator/text/write-text-transform.mjs',
  'src/creator/text/write-text-roll.mjs',
  'src/creator/text/write-text-controls.mjs',
  'src/creator/text/write-text-positioning.mjs',
  'src/creator/text/write-text-layout.mjs',
  'src/creator/storage/saved-card-data.mjs',
  'src/creator/imports/import-clipboard-text.mjs',
  'src/creator/imports/import-options.mjs',
  'src/creator/imports/import-search-options.mjs',
  'src/creator/imports/import-url.mjs',
  'src/creator/imports/import-card-basics.mjs',
  'src/creator/imports/import-printing.mjs',
  'src/creator/imports/import-text-preservation.mjs',
  'src/creator/imports/import-multi-faced.mjs',
  'src/creator/imports/import-unique-layout.mjs',
  'src/creator/imports/import-station-layout.mjs',
  'src/creator/imports/import-station-parser.mjs',
  'src/creator/imports/import-roll.mjs',
  'src/creator/imports/import-text-fields.mjs',
  'src/creator/imports/import-planeswalker.mjs',
  'src/creator/imports/import-saga.mjs',
  'src/creator/imports/import-class.mjs',
  'src/creator/imports/import-unique-layout-parsers.mjs',
  'src/creator/text/text-fields.mjs',
];

function moduleSourceToClassicScript(relativePath, source) {
  const classicSource = source
    .replace(/^import\s+[^;]+;\r?\n/gm, '')
    .replace(/^export function /gm, 'function ');

  return [
    `// BEGIN generated compat from ${relativePath}`,
    classicSource.trimEnd(),
    `// END generated compat from ${relativePath}`,
  ].join('\n');
}

export async function buildCreatorCompatPrelude() {
  const parts = [];

  for (const relativePath of creatorCompatModulePaths) {
    const source = await fsp.readFile(path.join(repoRoot, toNativePath(relativePath)), 'utf8');
    parts.push(moduleSourceToClassicScript(relativePath, source));
  }

  return [
    '// Generated by scripts/build.mjs from src/creator modules.',
    '// Do not edit this block in dist; update src/creator instead.',
    ...parts,
    '',
  ].join('\n');
}

export async function buildCreatorCompatScript(legacyRuntimeSource) {
  return `${await buildCreatorCompatPrelude()}${legacyRuntimeSource}`;
}
