name: publish

on:
  push:
    branches:
      - cn-release
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          files_ignore: |
            .github/**
            .git/**
            launcher*
            Makefile
            Dockerfile

      - name: Install OSS CLI
        run: |
          curl -o ossutil64 https://gosspublic.alicdn.com/ossutil/1.7.11/ossutil64
          chmod +x ossutil64
          sudo mv ossutil64 /usr/local/bin/ossutil

      - name: Configure OSS CLI
        run: |
          echo "[Credentials]" > ~/.ossutilconfig
          echo "accessKeyID=${{ secrets.ALIYUN_OSS_ACCESS_KEY_ID }}" >> ~/.ossutilconfig
          echo "accessKeySecret=${{ secrets.ALIYUN_OSS_ACCESS_KEY_SECRET }}" >> ~/.ossutilconfig
          echo "endpoint=${{ secrets.ALIYUN_OSS_ENDPOINT }}" >> ~/.ossutilconfig

      - name: Upload changed files to OSS
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            ossutil cp "$file" "oss://${{ secrets.ALIYUN_OSS_BUCKET }}/$file" -u --include "*"
          done

    env:
      ALIYUN_OSS_BUCKET: ${{ secrets.ALIYUN_OSS_BUCKET }}
      ALIYUN_OSS_ACCESS_KEY_ID: ${{ secrets.ALIYUN_OSS_ACCESS_KEY_ID }}
      ALIYUN_OSS_ACCESS_KEY_SECRET: ${{ secrets.ALIYUN_OSS_ACCESS_KEY_SECRET }}
      ALIYUN_OSS_ENDPOINT: ${{ secrets.ALIYUN_OSS_ENDPOINT }}